adminUser:
  password: local:jenkinsx/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: Ijoosi123@gmail.com
  token: local:jenkinsx/pipelineUser:token
  username: RonanBot
prow:
  hmacToken: local:jenkinsx/prow:hmacToken
